version: '3.9'
services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
      - TZ=Asia/Dhaka  # define your timezone
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf        
    networks:
      - WordPress_network
    restart: always

  database:
    image: mysql:8.0
    container_name: mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - TZ=Asia/Dhaka  # define your timezone
    volumes:
      - ./database:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - WordPress_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${HOST_PORT}:80"  # only mapped to the 80 port of the host 
    networks:
      - WordPress_network
    restart: always
    environment:
      TZ: Asia/Dhaka

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # if you need to access redis from the host, please map port 
    networks:
      - WordPress_network
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  # map the local configuration file to the container 
    command: redis-server /usr/local/etc/redis/redis.conf  # use a custom configuration file to start redis


networks:
  WordPress_network:
    driver: bridge
